name: Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    test:
        runs-on: ${{ matrix.os }}
        defaults:
            run:
                shell: bash -e {0} # -e to fail on error

        strategy:
            fail-fast: false
            matrix:
                python: ["3.10"]
                os: [ubuntu-latest]
                r: ["4.2"]

        env:
            OS: ${{ matrix.os }}
            PYTHON: ${{ matrix.python }}
            R: ${{ matrix.r }}
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.python }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python }}
            - name: Set up R ${{ matrix.r }}
              uses: r-lib/actions/setup-r@v2
              with:
                  r-version: ${{ matrix.r }}
            - name: Get pip cache dir
              id: pip-cache-dir
              run: |
                  echo "::set-output name=dir::$(pip cache dir)"
            - name: Restore pip cache
              uses: actions/cache@v2
              with:
                  path: ${{ steps.pip-cache-dir.outputs.dir }}
                  key: pip-${{ runner.os }}-${{ env.pythonLocation }}-${{ hashFiles('**/pyproject.toml') }}
                  restore-keys: |
                      pip-${{ runner.os }}-${{ env.pythonLocation }}-
            - name: Install test dependencies
              run: |
                  python -m pip install --upgrade pip wheel
            - name: Install dependencies
              run: |
                  pip install ".[dev,test]"
            - name: Update system dependencies
              # due to recent versions of GLIBC missing
              run: |
                  sudo apt-get update && sudo apt-get install cmake libstdc++6 \
                  libcurl4-openssl-dev libssl-dev libxml2-dev libfontconfig1-dev \
                  libharfbuzz-dev libfribidi-dev \
                  libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev -y
              # Cache R packages
            - name: Cache R packages
              uses: actions/cache@v2
              with:
                  path: ${{ env.R_LIBS_USER }}
                  key: ${{ runner.os }}-${{ hashFiles('**/lock-files.R') }}
                  restore-keys: ${{ runner.os }}-

              # Cache RScript
            - name: Cache RScript
              uses: actions/cache@v2
              with:
                  path: scripts
                  key: ${{ runner.os }}-${{ hashFiles('**/*.R') }}
                  restore-keys: ${{ runner.os }}-
            - name: Run RScript
              run: Rscript scripts/rscript.R
            - name: Test
              env:
                  MPLBACKEND: agg
                  PLATFORM: ${{ matrix.os }}
                  DISPLAY: :42
              run: |
                  pytest -v --cov --color=yes
